# Ansible Inventory generated by Terraform
all:
  vars:
    ansible_connection: local
    resource_group_name: ${resource_group_name}
    
  children:
    azure_app_services:
      hosts:
        portfolio_api:
          api_app_name: ${api_app_name}
  
    azure_acr:
      hosts:
        portfolio_acr:
          acr_name: ${acr_name}
          acr_login_server: ${acr_login_server}
          acr_username: ${acr_username}
          acr_password: ${acr_password}
          
    azure_storage:
      hosts:
        portfolio_storage:
          storage_account: ${storage_account}
          
    azure_sql:
      hosts:
        portfolio_db:
          sql_server_fqdn: ${sql_server_fqdn}
          sql_database: ${sql_database}
          sql_admin_login: ${sql_admin_login}
          sql_admin_password: ${sql_admin_password}
